development:
  twitter:
    key: T0ONiGrNuMNsKb5AyNC05mOpe
    secret: FxrQ6ddvlVbIaUlvEm0xg4fgoK9ACmWWnkesdU60ck1vJFoBM8
test:
  twitter:
    key: T0ONiGrNuMNsKb5AyNC05mOpe
    secret: FxrQ6ddvlVbIaUlvEm0xg4fgoK9ACmWWnkesdU60ck1vJFoBM8
production:
  twitter:
    key: T0ONiGrNuMNsKb5AyNC05mOpe
    secret: FxrQ6ddvlVbIaUlvEm0xg4fgoK9ACmWWnkesdU60ck1vJFoBM8
